from typing import Optional, ClassVar, Awaitable

import tornado.websocket
from transitions_gui import WebMachine

class MainHandler(tornado.web.RequestHandler):
    machine: WebMachine
    def initialize(self, machine) -> None: ...
    def get(self) -> None: ...

class WebSocketHandler(tornado.websocket.WebSocketHandler):
    sockets: ClassVar[set]
    machine: Optional[WebMachine]

    @classmethod
    def send_message(cls, message) -> None: ...
    def initialize(self, machine: WebMachine) -> None: ...
    def open(self, *args: str, **kwargs: str) -> Optional[Awaitable[None]]: ...
    def on_message(self, message) -> None: ...
    def on_close(self) -> None: ...
